from django.urls import path

from . import revenue_report_views, views

urlpatterns = [
    path('', views.don_ban_list, name='don_ban_list'),
    path('them/', views.don_ban_them, name='don_ban_them'),
    path('export-data/', views.don_ban_export_data, name='don_ban_export_data'),
    path('export-template/', views.don_ban_export_template, name='don_ban_export_template'),
    path('import-excel/', views.don_ban_import_excel, name='don_ban_import_excel'),
    path('api/khach-hang/', views.khach_hang_lookup, name='khach_hang_lookup'),
    path('api/khach-hang-lookup/', views.khach_hang_api_lookup, name='khach_hang_api_lookup'),
    path('api/don-ban-lookup/', views.don_ban_api_lookup, name='don_ban_api_lookup'),
    path('api/hoa-don-ban-lookup/', views.hoa_don_ban_api_lookup, name='hoa_don_ban_api_lookup'),
    path('api/hoa-don-ban/<int:pk>/', views.hoa_don_ban_api_detail, name='hoa_don_ban_api_detail'),
    path('api/don-ban/<int:pk>/', views.don_ban_api_detail, name='don_ban_api_detail'),
    path('<int:pk>/', views.don_ban_detail, name='don_ban_detail'),
    path('<int:pk>/sua/', views.don_ban_sua, name='don_ban_sua'),
    path('<int:pk>/xoa/', views.don_ban_xoa, name='don_ban_xoa'),
    path('xoa-nhieu/', views.don_ban_xoa_nhieu, name='don_ban_xoa_nhieu'),
    path('<int:pk>/so-cai/', views.don_ban_chuyen_so_cai, name='don_ban_chuyen_so_cai'),

    path('hoa-don/', views.hoa_don_ban_list, name='hoa_don_ban_list'),
    path('hoa-don/them/', views.hoa_don_ban_them, name='hoa_don_ban_them'),
    path('hoa-don/export-data/', views.hoa_don_ban_export_data, name='hoa_don_ban_export_data'),
    path('hoa-don/export-template/', views.hoa_don_ban_export_template, name='hoa_don_ban_export_template'),
    path('hoa-don/import-excel/', views.hoa_don_ban_import_excel, name='hoa_don_ban_import_excel'),
    path('hoa-don/<int:pk>/', views.hoa_don_ban_detail, name='hoa_don_ban_detail'),
    path('hoa-don/<int:pk>/copy/', views.hoa_don_ban_copy, name='hoa_don_ban_copy'),
    path('hoa-don/<int:pk>/sua/', views.hoa_don_ban_sua, name='hoa_don_ban_sua'),
    path('hoa-don/<int:pk>/xoa/', views.hoa_don_ban_xoa, name='hoa_don_ban_xoa'),
    path('hoa-don/xoa-nhieu/', views.hoa_don_ban_xoa_nhieu, name='hoa_don_ban_xoa_nhieu'),
    path('hoa-don/<int:pk>/so-cai/', views.hoa_don_ban_chuyen_so_cai, name='hoa_don_ban_chuyen_so_cai'),
    path('hoa-don/<int:pk>/in/', views.hoa_don_ban_in, name='hoa_don_ban_in'),

    path('gia-ban/', views.gia_ban_list, name='gia_ban_list'),
    path('gia-ban/them/', views.gia_ban_them, name='gia_ban_them'),
    path('gia-ban/<int:pk>/', views.gia_ban_detail, name='gia_ban_detail'),
    path('gia-ban/export-template/', views.gia_ban_export_template, name='gia_ban_export_template'),
    path('gia-ban/import-excel/', views.gia_ban_import_excel, name='gia_ban_import_excel'),
    path('gia-ban/<int:pk>/copy/', views.gia_ban_copy, name='gia_ban_copy'),
    path('gia-ban/<int:pk>/sua/', views.gia_ban_sua, name='gia_ban_sua'),
    path('gia-ban/<int:pk>/xoa/', views.gia_ban_xoa, name='gia_ban_xoa'),
    path('gia-ban/api/hang-hoa/', views.gia_ban_hang_hoa_api, name='gia_ban_hang_hoa_api'),

    path('phieu-thu/', views.phieu_thu_list, name='phieu_thu_list'),
    path('phieu-thu/them/', views.phieu_thu_them, name='phieu_thu_them'),
    path('phieu-thu/<int:pk>/xem/', views.phieu_thu_xem, name='phieu_thu_xem'),
    path('phieu-thu/<int:pk>/sua/', views.phieu_thu_sua, name='phieu_thu_sua'),
    path('phieu-thu/<int:pk>/xoa/', views.phieu_thu_xoa, name='phieu_thu_xoa'),
    path('phieu-thu/xoa-nhieu/', views.phieu_thu_xoa_nhieu, name='phieu_thu_xoa_nhieu'),
    path('phieu-chi/', views.phieu_thu_list, {'mode': 'chi'}, name='bh_phieu_chi_list'),
    path('phieu-chi/them/', views.phieu_thu_them, {'mode': 'chi'}, name='bh_phieu_chi_them'),
    path('phieu-chi/<int:pk>/xem/', views.phieu_thu_xem, {'mode': 'chi'}, name='bh_phieu_chi_xem'),
    path('phieu-chi/<int:pk>/sua/', views.phieu_thu_sua, {'mode': 'chi'}, name='bh_phieu_chi_sua'),
    path('phieu-chi/<int:pk>/xoa/', views.phieu_thu_xoa, {'mode': 'chi'}, name='bh_phieu_chi_xoa'),
    path('phieu-chi/xoa-nhieu/', views.phieu_thu_xoa_nhieu, {'mode': 'chi'}, name='bh_phieu_chi_xoa_nhieu'),
    path('phieu-thu/<int:pk>/xac-nhan/', views.phieu_thu_xac_nhan, name='phieu_thu_xac_nhan'),
    path('phieu-thu/<int:pk>/so-cai/', views.phieu_thu_chuyen_so_cai, name='phieu_thu_chuyen_so_cai'),
    path('doi-tra/', views.phieu_doi_tra_list, name='phieu_doi_tra_list'),
    path('doi-tra/them/', views.phieu_doi_tra_them, name='phieu_doi_tra_them'),
    path('doi-tra/<int:pk>/sua/', views.phieu_doi_tra_sua, name='phieu_doi_tra_sua'),
    path('doi-tra/<int:pk>/xoa/', views.phieu_doi_tra_xoa, name='phieu_doi_tra_xoa'),
    path('doi-tra/xoa-nhieu/', views.phieu_doi_tra_xoa_nhieu, name='phieu_doi_tra_xoa_nhieu'),
    path('doi-tra/api/hoa-don/<int:pk>/', views.doi_tra_hoa_don_detail_api, name='doi_tra_hoa_don_detail_api'),
    path('cong-no/', views.cong_no_kh, name='cong_no_kh'),
    path('bao-cao-cong-no-khach-hang-chi-tiet/', views.bao_cao_cong_no_kh_chi_tiet, name='bao_cao_cong_no_kh_ct'),
    path('bao-cao/doanh-thu/', views.bao_cao_doanh_thu, name='bao_cao_doanh_thu'),
    path('bao-cao/doanh-thu/api/summary/', revenue_report_views.revenue_summary_api, name='revenue_summary_api'),
    path('bao-cao/doanh-thu/api/by-customer/', revenue_report_views.revenue_by_customer_api, name='revenue_by_customer_api'),
    path('bao-cao/doanh-thu/api/by-product/', revenue_report_views.revenue_by_product_api, name='revenue_by_product_api'),
    path('bao-cao/doanh-thu/api/by-salesperson/', revenue_report_views.revenue_by_salesperson_api, name='revenue_by_salesperson_api'),
    path('bao-cao/doanh-thu/export-excel/', revenue_report_views.revenue_export_excel, name='revenue_export_excel'),

    # Phiếu giao hàng
    path('giao-hang/', views.phieu_giao_hang_list, name='phieu_giao_hang_list'),
    path('giao-hang/them/', views.phieu_giao_hang_them, name='phieu_giao_hang_them'),
    path('giao-hang/<int:pk>/sua/', views.phieu_giao_hang_sua, name='phieu_giao_hang_sua'),
    path('giao-hang/<int:pk>/xoa/', views.phieu_giao_hang_xoa, name='phieu_giao_hang_xoa'),
    path('giao-hang/api/hoa-don/<int:pk>/', views.phieu_giao_hang_api_hoa_don, name='phieu_giao_hang_api_hoa_don'),
]

