# Generated by Django 5.1.6 on 2026-03-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NhaCungCap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_ncc', models.CharField(max_length=20, unique=True, verbose_name='Mã NCC')),
                ('ten_ncc', models.CharField(max_length=200, verbose_name='Tên nhà cung cấp')),
                ('loai_ncc', models.CharField(choices=[('nha_sx', 'Nhà sản xuất'), ('dai_ly', 'Đại lý phân phối'), ('nhap_khau', 'Nhập khẩu')], default='dai_ly', max_length=20, verbose_name='Loại NCC')),
                ('ma_so_thue', models.CharField(blank=True, max_length=20, verbose_name='MST')),
                ('dia_chi', models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, verbose_name='SĐT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('nguoi_lien_he', models.CharField(blank=True, max_length=100, verbose_name='Người liên hệ')),
                ('so_tk_ngan_hang', models.CharField(blank=True, max_length=50, verbose_name='Số TK NH')),
                ('ngan_hang', models.CharField(blank=True, max_length=100, verbose_name='Ngân hàng')),
                ('so_ngay_thanh_toan', models.IntegerField(default=30, verbose_name='Số ngày TT')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Nhà cung cấp',
                'verbose_name_plural': 'Danh sách nhà cung cấp',
                'ordering': ['ma_ncc'],
            },
        ),
        migrations.CreateModel(
            name='NhomKhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_nhom', models.CharField(max_length=100, verbose_name='Tên nhóm KH')),
            ],
            options={
                'verbose_name': 'Nhóm khách hàng',
            },
        ),
        migrations.CreateModel(
            name='KhachHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kh', models.CharField(max_length=20, unique=True, verbose_name='Mã KH')),
                ('ten_kh', models.CharField(max_length=200, verbose_name='Tên khách hàng')),
                ('loai_kh', models.CharField(choices=[('ca_nhan', 'Cá nhân'), ('doanh_nghiep', 'Doanh nghiệp'), ('gara', 'Gara/Xưởng')], default='ca_nhan', max_length=20, verbose_name='Loại KH')),
                ('ma_so_thue', models.CharField(blank=True, max_length=20, verbose_name='MST')),
                ('dia_chi', models.CharField(blank=True, max_length=300, verbose_name='Địa chỉ')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='SĐT')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('han_muc_cong_no', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Hạn mức công nợ')),
                ('so_ngay_no_max', models.IntegerField(default=0, verbose_name='Số ngày nợ tối đa')),
                ('chiet_khau_mac_dinh', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CK mặc định (%)')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Hoạt động')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('nhom_kh', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.nhomkhachhang', verbose_name='Nhóm KH')),
            ],
            options={
                'verbose_name': 'Khách hàng',
                'verbose_name_plural': 'Danh sách khách hàng',
                'ordering': ['ma_kh'],
            },
        ),
    ]
