# Generated by Django 5.1.6 on 2026-04-08 08:55

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0007_taikhoan_va_ncc_hanghoa'),
    ]

    operations = [
        migrations.AddField(
            model_name='khachhang',
            name='la_khach_hang',
            field=models.BooleanField(default=True, verbose_name='Khách hàng'),
        ),
        migrations.AddField(
            model_name='khachhang',
            name='la_nha_cung_cap',
            field=models.BooleanField(default=False, verbose_name='Nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='hanghoa',
            name='muc_chiem_cho',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)], verbose_name='Mức chiếm chỗ (1-50)'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='chiet_khau_mac_dinh',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Chiết khấu mặc định (%)'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='loai_kh',
            field=models.CharField(choices=[('1', 'Cá nhân'), ('2', 'Doanh nghiệp'), ('3', 'Khác')], default='1', max_length=20, verbose_name='Loại khách hàng'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='ma_kh',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã khách hàng'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='ma_so_thue',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='nhom_kh',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.nhomkhachhang', verbose_name='Nhóm khách hàng'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='so_dien_thoai',
            field=models.CharField(max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='khachhang',
            name='trang_thai',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='loai_ncc',
            field=models.CharField(choices=[('nha_sx', 'Nhà sản xuất'), ('dai_ly', 'Đại lý phân phối'), ('nhap_khau', 'Nhập khẩu')], default='dai_ly', max_length=20, verbose_name='Loại nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='ma_ncc',
            field=models.CharField(max_length=20, unique=True, verbose_name='Mã nhà cung cấp'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='ma_so_thue',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã số thuế'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='so_dien_thoai',
            field=models.CharField(blank=True, max_length=15, verbose_name='Số điện thoại'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='so_ngay_thanh_toan',
            field=models.IntegerField(default=30, verbose_name='Số ngày thanh toán'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='so_tk_ngan_hang',
            field=models.CharField(blank=True, max_length=50, verbose_name='Số tài khoản ngân hàng'),
        ),
        migrations.AlterField(
            model_name='nhacungcap',
            name='trang_thai',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='nhomkhachhang',
            name='ten_nhom',
            field=models.CharField(max_length=100, verbose_name='Tên nhóm khách hàng'),
        ),
        migrations.AlterModelTable(
            name='khachhang',
            table='danh_muc_khachhang',
        ),
        migrations.AlterModelTable(
            name='nhacungcap',
            table='danh_muc_nhacungcap',
        ),
        migrations.AlterModelTable(
            name='nhomkhachhang',
            table='danh_muc_nhomkhachhang',
        ),
    ]
