# Generated by Django 5.1.6 on 2026-04-09 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0008_khachhang_la_khach_hang_khachhang_la_nha_cung_cap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhomhang',
            name='bien_do_loi_nhuan',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Biên độ lợi nhuận (%)'),
        ),
    ]
