# Generated by Django 5.1.6 on 2026-03-13 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DonViTinh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=50, unique=True, verbose_name='ĐVT')),
            ],
            options={
                'verbose_name': 'Đơn vị tính',
            },
        ),
        migrations.CreateModel(
            name='Kho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_kho', models.CharField(max_length=10, unique=True, verbose_name='Mã kho')),
                ('ten_kho', models.CharField(max_length=100, verbose_name='Tên kho')),
                ('dia_chi', models.CharField(blank=True, max_length=200, verbose_name='Địa chỉ')),
                ('trang_thai', models.BooleanField(default=True, verbose_name='Hoạt động')),
            ],
            options={
                'verbose_name': 'Kho',
                'ordering': ['ma_kho'],
            },
        ),
        migrations.CreateModel(
            name='NhomHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_nhom', models.CharField(max_length=20, unique=True, verbose_name='Mã nhóm')),
                ('ten_nhom', models.CharField(max_length=100, verbose_name='Tên nhóm hàng')),
                ('mo_ta', models.TextField(blank=True, verbose_name='Mô tả')),
            ],
            options={
                'verbose_name': 'Nhóm hàng',
                'verbose_name_plural': 'Nhóm hàng',
                'ordering': ['ten_nhom'],
            },
        ),
        migrations.CreateModel(
            name='ThuongHieu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100, unique=True, verbose_name='Thương hiệu')),
                ('nuoc_san_xuat', models.CharField(blank=True, max_length=100, verbose_name='Nước SX')),
            ],
            options={
                'verbose_name': 'Thương hiệu',
                'ordering': ['ten'],
            },
        ),
        migrations.CreateModel(
            name='HangHoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_hang', models.CharField(max_length=20, unique=True, verbose_name='Mã hàng')),
                ('ten_hang', models.CharField(max_length=200, verbose_name='Tên hàng hóa')),
                ('xe_tuong_thich', models.CharField(blank=True, max_length=500, verbose_name='Xe tương thích')),
                ('barcode', models.CharField(blank=True, max_length=50, verbose_name='Barcode')),
                ('gia_ban_le', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá bán lẻ')),
                ('gia_ban_buon', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá bán buôn')),
                ('ton_toi_thieu', models.IntegerField(default=0, verbose_name='Tồn tối thiểu')),
                ('ton_toi_da', models.IntegerField(default=0, verbose_name='Tồn tối đa')),
                ('trang_thai', models.CharField(choices=[('dang_ban', 'Đang bán'), ('ngung_ban', 'Ngừng bán')], default='dang_ban', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('don_vi_tinh', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.donvitinh', verbose_name='ĐVT')),
                ('nhom_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.nhomhang', verbose_name='Nhóm hàng')),
                ('thuong_hieu', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.thuonghieu', verbose_name='Thương hiệu')),
            ],
            options={
                'verbose_name': 'Hàng hóa',
                'verbose_name_plural': 'Danh sách hàng hóa',
                'ordering': ['ma_hang'],
            },
        ),
        migrations.CreateModel(
            name='ViTriKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_vi_tri', models.CharField(max_length=20, verbose_name='Mã vị trí')),
                ('mo_ta', models.CharField(blank=True, max_length=100, verbose_name='Mô tả')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kho', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Vị trí kho',
                'unique_together': {('kho', 'ma_vi_tri')},
            },
        ),
    ]
