# Generated by Django 5.1.6 on 2026-03-13 16:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('danh_muc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_don', models.CharField(max_length=30, unique=True, verbose_name='Số đơn bán')),
                ('ngay_ban', models.DateField(default=datetime.date.today, verbose_name='Ngày bán')),
                ('loai_ban', models.CharField(choices=[('ban_le', 'Bán lẻ'), ('ban_buon', 'Bán buôn'), ('ban_gara', 'Bán gara/xưởng')], default='ban_le', max_length=20, verbose_name='Loại bán')),
                ('ten_kh', models.CharField(blank=True, max_length=200, verbose_name='Tên KH')),
                ('sdt_kh', models.CharField(blank=True, max_length=15, verbose_name='SĐT KH')),
                ('xe_kh', models.CharField(blank=True, max_length=100, verbose_name='Xe KH')),
                ('phuong_thuc_tt', models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản'), ('no', 'Ghi nợ')], default='tien_mat', max_length=20, verbose_name='PTTT')),
                ('tong_tien_hang', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('chiet_khau_dh', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Chiết khấu đơn hàng')),
                ('tong_thue', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tong_thanh_toan', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng thanh toán')),
                ('da_thu', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Đã thu')),
                ('con_no', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Còn nợ')),
                ('trang_thai', models.CharField(choices=[('nhap', 'Nháp'), ('da_xac_nhan', 'Đã xác nhận'), ('huy', 'Đã hủy')], default='nhap', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.khachhang', verbose_name='Khách hàng')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kho', verbose_name='Kho xuất')),
                ('nhan_vien_ban', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nhân viên bán')),
            ],
            options={
                'verbose_name': 'Đơn bán hàng',
                'verbose_name_plural': 'Đơn bán hàng',
                'ordering': ['-ngay_ban', '-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='DonBan_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(verbose_name='Số lượng')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Đơn giá')),
                ('chiet_khau', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CK (%)')),
                ('thue_vat', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='VAT (%)')),
                ('thanh_tien', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Thành tiền')),
                ('tien_thue', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tiền thuế')),
                ('gia_von', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá vốn')),
                ('loi_nhuan', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Lợi nhuận')),
                ('don_ban', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='ban_hang.donban', verbose_name='Đơn bán')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hanghoa', verbose_name='Hàng hóa')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn bán',
            },
        ),
        migrations.CreateModel(
            name='PhieuThu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu thu')),
                ('ngay_thu', models.DateField(default=datetime.date.today, verbose_name='Ngày thu')),
                ('hinh_thuc_thu', models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản')], default='tien_mat', max_length=20)),
                ('so_tk_nh', models.CharField(blank=True, max_length=100, verbose_name='Số TK NH')),
                ('so_tham_chieu', models.CharField(blank=True, max_length=100, verbose_name='Mã GD')),
                ('tong_thu', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Số tiền thu')),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('don_ban', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ban_hang.donban', verbose_name='Đơn bán hàng')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.khachhang', verbose_name='Khách hàng')),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiếu thu tiền',
                'ordering': ['-ngay_thu'],
            },
        ),
        migrations.CreateModel(
            name='PhieuTraHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu trả')),
                ('ngay_tra', models.DateField(default=datetime.date.today, verbose_name='Ngày trả')),
                ('ly_do_tra', models.CharField(max_length=200, verbose_name='Lý do trả hàng')),
                ('hinh_thuc_hoan', models.CharField(choices=[('tien_mat', 'Hoàn tiền mặt'), ('bu_tru_no', 'Bù trừ công nợ'), ('doi_hang', 'Đổi hàng khác')], default='tien_mat', max_length=20)),
                ('tong_tien_hoan', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền hoàn')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('don_ban_goc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ban_hang.donban', verbose_name='Đơn bán gốc')),
                ('khach_hang', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.khachhang', verbose_name='Khách hàng')),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Phiếu trả hàng',
                'ordering': ['-ngay_tra'],
            },
        ),
        migrations.CreateModel(
            name='PhieuTraHang_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField()),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=18)),
                ('thanh_tien', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hanghoa')),
                ('phieu_tra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='ban_hang.phieutrahang')),
            ],
        ),
    ]
