# Generated by Django 5.1.6 on 2026-04-09 16:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0006_donban_status_4step'),
        ('danh_muc', '0009_nhomhang_bien_do_loi_nhuan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donban',
            table='ban_hang_donban',
        ),
        migrations.AlterModelTable(
            name='donban_ct',
            table='ban_hang_donban_ct',
        ),
        migrations.AlterModelTable(
            name='phieuthu',
            table='ban_hang_phieuthu',
        ),
        migrations.AlterModelTable(
            name='phieutrahang',
            table='ban_hang_phieutrahang',
        ),
        migrations.AlterModelTable(
            name='phieutrahang_ct',
            table='ban_hang_phieutrahang_ct',
        ),
        migrations.CreateModel(
            name='PhieuGiaBan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ma_phieu', models.CharField(max_length=30, unique=True, verbose_name='Mã phiếu giá bán')),
                ('ngay_lap', models.DateField(default=datetime.date.today, verbose_name='Ngày lập')),
                ('ngay_hieu_luc', models.DateField(verbose_name='Ngày hiệu lực')),
                ('bien_do_loi_nhuan', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='Biên độ lợi nhuận (%)')),
                ('loai_tien_te', models.CharField(choices=[('VND', 'VND'), ('USD', 'USD')], default='VND', max_length=10, verbose_name='Loại tiền tệ')),
                ('trang_thai_duyet', models.CharField(choices=[('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('tu_choi', 'Từ chối')], default='cho_duyet', max_length=20, verbose_name='Trạng thái duyệt')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True, verbose_name='Ngày tạo')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True, verbose_name='Ngày cập nhật')),
                ('nguoi_lap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_gia_ban_lap', to=settings.AUTH_USER_MODEL, verbose_name='Người lập')),
                ('nhom_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.nhomhang', verbose_name='Nhóm hàng')),
            ],
            options={
                'verbose_name': 'Phiếu giá bán',
                'db_table': 'ban_hang_phieu_gia_ban',
                'ordering': ['-ngay_lap', '-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='PhieuGiaBanChietKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tu_so_luong', models.IntegerField(verbose_name='Từ số lượng')),
                ('den_so_luong', models.IntegerField(verbose_name='Đến số lượng')),
                ('phan_tram_chiet_khau', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='% chiết khấu')),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bang_chiet_khau', to='ban_hang.phieugiaban', verbose_name='Phiếu giá bán')),
            ],
            options={
                'verbose_name': 'Bảng chiết khấu',
                'db_table': 'ban_hang_phieu_gia_ban_ck',
                'ordering': ['tu_so_luong'],
            },
        ),
        migrations.CreateModel(
            name='PhieuGiaBan_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gia_von', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá vốn')),
                ('gia_ban_chuan', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá bán chuẩn')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.hanghoa', verbose_name='Mặt hàng')),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='ban_hang.phieugiaban', verbose_name='Phiếu giá bán')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu giá bán',
                'db_table': 'ban_hang_phieu_gia_ban_ct',
                'unique_together': {('phieu', 'hang_hoa')},
            },
        ),
    ]
