# Generated by Django 5.1.6 on 2026-04-13 01:55

import datetime

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0012_hoadonban_inventory_and_detail_accounts'),
        ('danh_muc', '0010_khachhang_la_nhan_vien'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieutrahang',
            name='chenh_lech_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Chênh lệch tiền'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='da_cap_nhat_kho_cong_no',
            field=models.BooleanField(default=False, verbose_name='Đã cập nhật kho/công nợ'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='dien_giai',
            field=models.TextField(blank=True, verbose_name='Diễn giải'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='hinh_thuc_xu_ly',
            field=models.CharField(choices=[('doi_hang', 'Đổi hàng'), ('tra_hang', 'Trả hàng')], default='tra_hang', max_length=20, verbose_name='Hình thức'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='hoa_don_goc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='phieu_doi_tra', to='ban_hang.hoadonban', verbose_name='Hóa đơn gốc'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='ngay_hach_toan',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày hạch toán'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='ngay_lap',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày lập'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='tk_co',
            field=models.CharField(default='131', max_length=20, verbose_name='TK có'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='tong_tien_doi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền hàng đổi'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='tong_tien_tra',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền hàng trả'),
        ),
        migrations.AddField(
            model_name='phieutrahang',
            name='trang_thai',
            field=models.CharField(choices=[('1', '1 - Lập chứng từ'), ('2', '2 - Hoàn tất')], default='1', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AddField(
            model_name='phieutrahang_ct',
            name='gia_ban_doi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='phieutrahang_ct',
            name='hang_hoa_doi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chi_tiet_hang_doi', to='danh_muc.hanghoa'),
        ),
        migrations.AddField(
            model_name='phieutrahang_ct',
            name='hoa_don_ct_goc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chi_tiet_doi_tra', to='ban_hang.hoadonban_ct'),
        ),
        migrations.AddField(
            model_name='phieutrahang_ct',
            name='kho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='danh_muc.kho', verbose_name='Kho xử lý'),
        ),
        migrations.AddField(
            model_name='phieutrahang_ct',
            name='loai_hang_tra',
            field=models.CharField(choices=[('binh_thuong', 'Hàng bình thường'), ('hang_loi', 'Hàng lỗi')], default='binh_thuong', max_length=20),
        ),
        migrations.AddField(
            model_name='phieutrahang_ct',
            name='so_luong_doi',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phieutrahang_ct',
            name='tien_doi',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18),
        ),
    ]
