# Generated by Django 5.1.6 on 2026-04-13 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0013_phieutrahang_chenh_lech_tien_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hoadonban',
            name='ma_giao_dich',
            field=models.CharField(choices=[('1', '1 - Hóa đơn kiêm phiếu xuất bán'), ('2', '2 - Hóa đơn')], default='1', max_length=5, verbose_name='Mã giao dịch'),
        ),
        migrations.AlterField(
            model_name='hoadonban',
            name='trang_thai',
            field=models.CharField(choices=[('1', '1 - Lập chứng từ'), ('2', '2 - Chuyển sổ cái')], default='1', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='phieuthu',
            name='trang_thai',
            field=models.CharField(choices=[('1', '1 - Lập chứng từ'), ('2', '2 - Chuyển sổ cái')], default='1', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='phieutrahang',
            name='hinh_thuc_hoan',
            field=models.CharField(choices=[('1', '1 - Hoàn tiền mặt'), ('2', '2 - Bù trừ công nợ'), ('3', '3 - Đổi hàng khác')], default='1', max_length=20),
        ),
    ]
