# Generated by Django 5.1.6 on 2026-04-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0014_alter_hoadonban_ma_giao_dich_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieutrahang',
            name='tk_no',
            field=models.CharField(default='131', max_length=20, verbose_name='TK nợ'),
        ),
    ]