# Generated by Django 5.1.6 on 2026-04-15 16:45

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0015_phieutrahang_tk_no'),
        ('danh_muc', '0010_khachhang_la_nhan_vien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhieuGiaoHang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu giao hàng')),
                ('ngay_lap', models.DateField(default=datetime.date.today, verbose_name='Ngày lập')),
                ('ten_kh', models.CharField(blank=True, max_length=200, verbose_name='Tên khách')),
                ('nguoi_nhan', models.CharField(blank=True, max_length=200, verbose_name='Người nhận')),
                ('dien_giai', models.TextField(blank=True, verbose_name='Diễn giải')),
                ('trang_thai', models.CharField(choices=[('cho_giao', 'Chờ giao hàng'), ('da_giao', 'Đã giao hàng')], default='cho_giao', max_length=20, verbose_name='Trạng thái')),
                ('tong_so_luong', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Tổng số lượng')),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('hoa_don_goc', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phieu_giao_hang', to='ban_hang.hoadonban', verbose_name='Hóa đơn liên kết')),
                ('khach_hang', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.khachhang', verbose_name='Khách hàng')),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu giao hàng',
                'verbose_name_plural': 'Phiếu giao hàng',
                'db_table': 'ban_hang_phieu_giao_hang',
                'ordering': ['-ngay_lap', '-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='PhieuGiaoHang_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vi_tri', models.CharField(blank=True, max_length=100, verbose_name='Mã vị trí')),
                ('so_luong', models.DecimalField(decimal_places=2, default=0, max_digits=18, verbose_name='Số lượng')),
                ('don_gia', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Đơn giá')),
                ('ngay_giao', models.DateField(default=datetime.date.today, verbose_name='Ngày giao')),
                ('loai_van_chuyen', models.CharField(choices=[('tu_giao', 'Tự giao'), ('doi_tac', 'Đối tác vận chuyển'), ('khach_tu_lay', 'Khách tự lấy')], default='tu_giao', max_length=30, verbose_name='Loại vận chuyển')),
                ('ghi_chu', models.CharField(blank=True, max_length=300, verbose_name='Ghi chú')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.hanghoa', verbose_name='Mã hàng')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.kho', verbose_name='Mã kho')),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='ban_hang.phieugiaohang', verbose_name='Phiếu giao hàng')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu giao hàng',
                'db_table': 'ban_hang_phieu_giao_hang_ct',
            },
        ),
    ]
