# Generated by Django 5.1.6 on 2026-04-18 01:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0017_add_tk_kho_to_hoadonban_ct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieuthu',
            name='don_ban',
        ),
        migrations.AddField(
            model_name='hoadonban',
            name='con_no',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Còn nợ'),
        ),
        migrations.AddField(
            model_name='hoadonban',
            name='da_thu',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Đã thu'),
        ),
        migrations.AddField(
            model_name='phieuthu',
            name='hoa_don',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ban_hang.hoadonban', verbose_name='Hóa đơn bán hàng'),
        ),
    ]
