# Generated by Django 5.1.6 on 2026-04-27 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0018_remove_phieuthu_don_ban_hoadonban_con_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='donban_ct',
            name='so_luong_da_giao',
            field=models.IntegerField(default=0, verbose_name='Số lượng đã giao'),
        ),
        migrations.AlterField(
            model_name='donban',
            name='trang_thai',
            field=models.CharField(choices=[('1', '1 - Lập chứng từ'), ('2', '2 - Treo')], default='1', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
