# Generated by Django 5.1.6 on 2026-04-27 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0019_add_so_luong_da_giao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donban',
            name='trang_thai',
            field=models.CharField(choices=[('1', '1 - Lập chứng từ'), ('2', '2 - Giao 1 phần'), ('3', '3 - Hoàn thành')], default='1', max_length=20, verbose_name='Trạng thái'),
        ),
    ]
