# Generated by Django 5.1.6 on 2026-04-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ban_hang', '0020_alter_donban_trang_thai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donban',
            name='loai_ban',
        ),
        migrations.RemoveField(
            model_name='donban',
            name='ma_ngoai_te',
        ),
        migrations.RemoveField(
            model_name='donban',
            name='phuong_thuc_tt',
        ),
        migrations.RemoveField(
            model_name='donban_ct',
            name='ngay_giao',
        ),
        migrations.RemoveField(
            model_name='hoadonban',
            name='ma_ngoai_te',
        ),
        migrations.RemoveField(
            model_name='phieuthu',
            name='hinh_thuc_thu',
        ),
        migrations.RemoveField(
            model_name='phieuthu',
            name='so_tk_nh',
        ),
        migrations.RemoveField(
            model_name='phieutrahang',
            name='don_ban_goc',
        ),
        migrations.RemoveField(
            model_name='phieutrahang',
            name='hinh_thuc_hoan',
        ),
        migrations.AlterField(
            model_name='phieutrahang',
            name='tk_co',
            field=models.CharField(default='', max_length=20, verbose_name='TK có'),
        ),
        migrations.AlterModelTable(
            name='congnocanhbaoconfig',
            table='ban_hang_congno_canhbao',
        ),
    ]
