# Generated by Django 5.1.6 on 2026-03-13 16:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('danh_muc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonMua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_don', models.CharField(max_length=30, unique=True, verbose_name='Số đơn mua')),
                ('ngay_dat', models.DateField(default=datetime.date.today, verbose_name='Ngày đặt')),
                ('ngay_giao_dk', models.DateField(blank=True, null=True, verbose_name='Ngày giao dự kiến')),
                ('ly_do', models.CharField(blank=True, max_length=200, verbose_name='Lý do đặt hàng')),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền')),
                ('trang_thai', models.CharField(choices=[('nhap', 'Nháp'), ('cho_duyet', 'Chờ duyệt'), ('da_duyet', 'Đã duyệt'), ('nhan_1_phan', 'Nhận một phần'), ('hoan_thanh', 'Hoàn thành'), ('huy', 'Đã hủy')], default='nhap', max_length=20, verbose_name='Trạng thái')),
                ('ngay_duyet', models.DateTimeField(blank=True, null=True, verbose_name='Ngày duyệt')),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kho', verbose_name='Kho nhận')),
                ('nguoi_duyet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_mua_duyet', to=settings.AUTH_USER_MODEL, verbose_name='Người duyệt')),
                ('nguoi_lap', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='don_mua_lap', to=settings.AUTH_USER_MODEL, verbose_name='Người lập')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Đơn đặt mua hàng',
                'ordering': ['-ngay_dat', '-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='DonMua_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_dat', models.IntegerField(verbose_name='SL đặt')),
                ('so_luong_da_nhan', models.IntegerField(default=0, verbose_name='SL đã nhận')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Đơn giá')),
                ('thue_vat', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='VAT (%)')),
                ('thanh_tien', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('don_mua', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='mua_hang.donmua', verbose_name='Đơn mua')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hanghoa', verbose_name='Hàng hóa')),
            ],
            options={
                'verbose_name': 'Chi tiết đơn mua',
            },
        ),
        migrations.CreateModel(
            name='HoaDonMuaVao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_hoa_don', models.CharField(max_length=30, unique=True, verbose_name='Số HĐ mua vào')),
                ('so_hd_ncc', models.CharField(blank=True, max_length=50, verbose_name='Số HĐ NCC')),
                ('ngay_hd', models.DateField(default=datetime.date.today, verbose_name='Ngày HĐ')),
                ('tong_tien_hang', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('thue_vat', models.DecimalField(decimal_places=0, default=0, max_digits=18)),
                ('tong_thanh_toan', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng TT')),
                ('da_thanh_toan', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Đã TT')),
                ('con_no', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Còn nợ')),
                ('han_thanh_toan', models.DateField(blank=True, null=True, verbose_name='Hạn TT')),
                ('trang_thai', models.CharField(choices=[('chua_tt', 'Chưa thanh toán'), ('tt_1_phan', 'TT một phần'), ('da_tt', 'Đã thanh toán')], default='chua_tt', max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('don_mua', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mua_hang.donmua', verbose_name='Đơn mua liên kết')),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Hóa đơn mua vào',
                'ordering': ['-ngay_hd'],
            },
        ),
        migrations.CreateModel(
            name='PhieuChi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu chi')),
                ('ngay_chi', models.DateField(default=datetime.date.today, verbose_name='Ngày chi')),
                ('hinh_thuc', models.CharField(choices=[('tien_mat', 'Tiền mặt'), ('chuyen_khoan', 'Chuyển khoản')], default='tien_mat', max_length=20)),
                ('so_tk_chi', models.CharField(blank=True, max_length=100, verbose_name='TK/NH chi')),
                ('so_tham_chieu', models.CharField(blank=True, max_length=100, verbose_name='Mã GD')),
                ('tong_chi', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Số tiền chi')),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('hoa_don_lien_ket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mua_hang.hoadonmuavao', verbose_name='Liên kết HĐ')),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('nha_cung_cap', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Phiếu chi tiền NCC',
                'ordering': ['-ngay_chi'],
            },
        ),
    ]
