# Generated by Django 5.1.6 on 2026-03-13 16:05

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('danh_muc', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_kiem_ke', models.DateField(default=datetime.date.today, verbose_name='Ngày kiểm kê')),
                ('nguoi_kiem', models.CharField(blank=True, max_length=100, verbose_name='Người kiểm kê')),
                ('trang_thai', models.CharField(choices=[('dang_kiem', 'Đang kiểm kê'), ('da_duyet', 'Đã duyệt & điều chỉnh')], default='dang_kiem', max_length=20)),
                ('ghi_chu', models.TextField(blank=True)),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kho', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Phiếu kiểm kê',
                'ordering': ['-ngay_kiem_ke'],
            },
        ),
        migrations.CreateModel(
            name='KiemKe_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_so_sach', models.IntegerField(verbose_name='SL sổ sách')),
                ('so_luong_thuc_te', models.IntegerField(verbose_name='SL thực tế')),
                ('chenh_lech', models.IntegerField(default=0, verbose_name='Chênh lệch')),
                ('ly_do', models.CharField(blank=True, max_length=200, verbose_name='Lý do chênh lệch')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hanghoa', verbose_name='Hàng hóa')),
                ('kiem_ke', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='kho.kiemke')),
            ],
        ),
        migrations.CreateModel(
            name='PhieuNhap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu nhập')),
                ('ngay_nhap', models.DateField(default=datetime.date.today, verbose_name='Ngày nhập')),
                ('loai_nhap', models.CharField(choices=[('mua_ncc', 'Mua nhà cung cấp'), ('tra_hang_kh', 'Khách hàng trả hàng'), ('dieu_chinh', 'Điều chỉnh tồn kho')], default='mua_ncc', max_length=20, verbose_name='Loại nhập')),
                ('so_hd_ncc', models.CharField(blank=True, max_length=50, verbose_name='Số HĐ NCC')),
                ('ngay_hd_ncc', models.DateField(blank=True, null=True, verbose_name='Ngày HĐ NCC')),
                ('tong_tien', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền')),
                ('trang_thai', models.CharField(choices=[('nhap', 'Nháp'), ('da_nhap', 'Đã nhập kho'), ('huy', 'Đã hủy')], default='nhap', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kho', verbose_name='Kho nhập')),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
                ('nha_cung_cap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.nhacungcap', verbose_name='Nhà cung cấp')),
            ],
            options={
                'verbose_name': 'Phiếu nhập kho',
                'verbose_name_plural': 'Phiếu nhập kho',
                'ordering': ['-ngay_nhap', '-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='PhieuNhap_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_dat', models.IntegerField(default=0, verbose_name='SL đặt')),
                ('so_luong_nhan', models.IntegerField(verbose_name='SL thực nhận')),
                ('don_gia', models.DecimalField(decimal_places=0, max_digits=18, verbose_name='Đơn giá')),
                ('chiet_khau', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='CK (%)')),
                ('thue_vat', models.DecimalField(decimal_places=2, default=10, max_digits=5, verbose_name='VAT (%)')),
                ('thanh_tien', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Thành tiền')),
                ('so_lo', models.CharField(blank=True, max_length=50, verbose_name='Số lô')),
                ('han_su_dung', models.DateField(blank=True, null=True, verbose_name='Hạn SD')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hanghoa', verbose_name='Hàng hóa')),
                ('phieu_nhap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='kho.phieunhap', verbose_name='Phiếu nhập')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu nhập',
            },
        ),
        migrations.CreateModel(
            name='PhieuXuat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu', models.CharField(max_length=30, unique=True, verbose_name='Số phiếu xuất')),
                ('ngay_xuat', models.DateField(default=datetime.date.today, verbose_name='Ngày xuất')),
                ('loai_xuat', models.CharField(choices=[('ban_hang', 'Xuất bán hàng'), ('tra_ncc', 'Trả nhà cung cấp'), ('noi_bo', 'Xuất nội bộ'), ('hu_hong', 'Hư hỏng / Hao hụt')], default='ban_hang', max_length=20, verbose_name='Loại xuất')),
                ('tong_gia_von', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng giá vốn')),
                ('trang_thai', models.CharField(choices=[('nhap', 'Nháp'), ('da_xuat', 'Đã xuất kho'), ('huy', 'Đã hủy')], default='nhap', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.TextField(blank=True, verbose_name='Ghi chú')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kho', verbose_name='Kho xuất')),
                ('nguoi_tao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Phiếu xuất kho',
                'ordering': ['-ngay_xuat', '-ngay_tao'],
            },
        ),
        migrations.CreateModel(
            name='PhieuXuat_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(verbose_name='Số lượng')),
                ('gia_von', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá vốn/đv')),
                ('tong_gia_von', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng giá vốn')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.hanghoa', verbose_name='Hàng hóa')),
                ('phieu_xuat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='kho.phieuxuat', verbose_name='Phiếu xuất')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu xuất',
            },
        ),
        migrations.CreateModel(
            name='TonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0, verbose_name='Số lượng tồn')),
                ('gia_von_tb', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá vốn TB')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hanghoa', verbose_name='Hàng hóa')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.kho', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Tồn kho',
                'unique_together': {('hang_hoa', 'kho')},
            },
        ),
    ]
