# Generated by Django 5.1.6 on 2026-04-08 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0008_khachhang_la_khach_hang_khachhang_la_nha_cung_cap_and_more'),
        ('kho', '0007_phieuxuatct_taikhoan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tonkho',
            name='so_luong_loi',
            field=models.IntegerField(default=0, verbose_name='Số lượng hàng lỗi'),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='loai_nhap',
            field=models.CharField(choices=[('1', 'Mua nhà cung cấp'), ('2', 'Khách hàng trả hàng'), ('3', 'Điều chỉnh tồn kho')], default='1', max_length=20, verbose_name='Loại nhập'),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='trang_thai',
            field=models.CharField(choices=[('1', '1 - Lập phiếu'), ('2', '2 - Sổ kho'), ('3', '3 - Sổ cái')], default='1', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterField(
            model_name='phieuxuat',
            name='trang_thai',
            field=models.CharField(choices=[('1', '1 - Lập phiếu'), ('2', '2 - Sổ kho'), ('3', '3 - Sổ cái')], default='1', max_length=20, verbose_name='Trạng thái'),
        ),
        migrations.AlterModelTable(
            name='kiemke',
            table='kho_kiemke',
        ),
        migrations.AlterModelTable(
            name='kiemke_ct',
            table='kho_kiemke_ct',
        ),
        migrations.AlterModelTable(
            name='phieunhap',
            table='kho_phieunhap',
        ),
        migrations.AlterModelTable(
            name='phieunhap_ct',
            table='kho_phieunhap_ct',
        ),
        migrations.AlterModelTable(
            name='phieuxuat',
            table='kho_phieuxuat',
        ),
        migrations.AlterModelTable(
            name='phieuxuat_ct',
            table='kho_phieuxuat_ct',
        ),
        migrations.AlterModelTable(
            name='tonkho',
            table='kho_tonkho',
        ),
        migrations.CreateModel(
            name='MucTonKho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ton_toi_thieu', models.IntegerField(default=0, verbose_name='Tồn tối thiểu')),
                ('ton_toi_da', models.IntegerField(blank=True, null=True, verbose_name='Tồn tối đa')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danh_muc.hanghoa', verbose_name='Hàng hóa')),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danh_muc.kho', verbose_name='Kho áp dụng')),
                ('nguoi_cap_nhat', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người cập nhật')),
            ],
            options={
                'verbose_name': 'Mức tồn kho',
                'verbose_name_plural': 'Mức tồn kho',
                'db_table': 'kho_muctonkho',
                'unique_together': {('hang_hoa', 'kho')},
            },
        ),
    ]
