# Generated by Django 5.1.6 on 2026-04-14 04:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0010_khachhang_la_nhan_vien'),
        ('kho', '0009_add_ngay_lap_hach_toan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='phieunhap',
            options={'ordering': ['-ngay_hach_toan', '-ngay_lap', '-ngay_tao'], 'verbose_name': 'Phiếu nhập kho', 'verbose_name_plural': 'Phiếu nhập kho'},
        ),
        migrations.AlterModelOptions(
            name='phieuxuat',
            options={'ordering': ['-ngay_hach_toan', '-ngay_lap', '-ngay_tao'], 'verbose_name': 'Phiếu xuất kho'},
        ),
        migrations.AddField(
            model_name='kiemke',
            name='khu_vuc',
            field=models.CharField(blank=True, max_length=120, verbose_name='Khu vực kiểm kê'),
        ),
        migrations.AddField(
            model_name='kiemke',
            name='ma_phieu',
            field=models.CharField(blank=True, max_length=30, unique=True, verbose_name='Mã phiếu kiểm kê'),
        ),
        migrations.AddField(
            model_name='kiemke',
            name='nhom_hang',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.nhomhang', verbose_name='Loại hàng hóa kiểm kê'),
        ),
        migrations.AddField(
            model_name='kiemke_ct',
            name='tinh_trang',
            field=models.CharField(choices=[('tot_100', 'Tốt 100%'), ('hu_hong', 'Hư hỏng'), ('thieu_hang', 'Thiếu hàng')], default='tot_100', max_length=20, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='kiemke',
            name='trang_thai',
            field=models.CharField(choices=[('1', '1 - Chờ kiểm kê'), ('2', '2 - Chờ điều chỉnh'), ('3', '3 - Hoàn thành')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='ngay_hach_toan',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày hạch toán'),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='ngay_lap',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày lập'),
        ),
        migrations.AlterField(
            model_name='phieuxuat',
            name='ngay_hach_toan',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày hạch toán'),
        ),
        migrations.AlterField(
            model_name='phieuxuat',
            name='ngay_lap',
            field=models.DateField(default=datetime.date.today, verbose_name='Ngày lập'),
        ),
        migrations.CreateModel(
            name='PhieuDieuChinhKiemKe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_phieu', models.CharField(max_length=30, unique=True, verbose_name='Mã phiếu điều chỉnh')),
                ('ngay_dieu_chinh', models.DateField(default=datetime.date.today, verbose_name='Ngày điều chỉnh')),
                ('ly_do', models.CharField(max_length=255, verbose_name='Lý do điều chỉnh')),
                ('trang_thai', models.CharField(choices=[('1', '1 - Chờ duyệt'), ('2', '2 - Đã duyệt')], default='1', max_length=20, verbose_name='Trạng thái')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('kho', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.kho', verbose_name='Kho')),
                ('kiem_ke', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='phieu_dieu_chinh', to='kho.kiemke')),
                ('nguoi_lap', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Người lập')),
            ],
            options={
                'verbose_name': 'Phiếu điều chỉnh kiểm kê',
                'db_table': 'kho_phieudieuchinh_kiemke',
                'ordering': ['-ngay_dieu_chinh', '-id'],
            },
        ),
        migrations.CreateModel(
            name='PhieuDieuChinhKiemKe_CT',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong_he_thong', models.IntegerField(verbose_name='SL hệ thống')),
                ('so_luong_thuc_te', models.IntegerField(verbose_name='SL thực tế')),
                ('chenh_lech', models.IntegerField(verbose_name='Chênh lệch')),
                ('ly_do', models.CharField(blank=True, max_length=255, verbose_name='Lý do điều chỉnh')),
                ('hang_hoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.hanghoa', verbose_name='Hàng hóa')),
                ('phieu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet', to='kho.phieudieuchinhkiemke')),
            ],
            options={
                'verbose_name': 'Chi tiết phiếu điều chỉnh kiểm kê',
                'db_table': 'kho_phieudieuchinh_kiemke_ct',
            },
        ),
    ]
