# Generated by Django 5.1.6 on 2026-04-14 19:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0010_khachhang_la_nhan_vien'),
        ('kho', '0010_alter_phieunhap_options_alter_phieuxuat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiemke',
            name='vi_tri_hang_loi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kiem_ke_hang_loi', to='danh_muc.vitrikho', verbose_name='Vị trí hàng lỗi'),
        ),
        migrations.AddField(
            model_name='kiemke_ct',
            name='so_luong_loi',
            field=models.IntegerField(default=0, verbose_name='SL hàng lỗi'),
        ),
    ]
