# Generated by Django 5.1.6 on 2026-04-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0011_kiemke_vi_tri_hang_loi_kiemke_ct_so_luong_loi'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieudieuchinhkiemke_ct',
            name='so_luong_loi',
            field=models.IntegerField(default=0, verbose_name='SL hàng lỗi'),
        ),
    ]
