# Generated by Django 5.1.6 on 2026-04-24 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0010_khachhang_la_nhan_vien'),
        ('kho', '0012_phieudieuchinhkiemke_ct_so_luong_loi'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieunhap_ct',
            name='vi_tri_uu_tien',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.vitrikho', verbose_name='Vị trí ưu tiên'),
        ),
    ]
