# Generated by Django 5.1.6 on 2026-04-24 06:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0010_khachhang_la_nhan_vien'),
        ('kho', '0013_phieunhap_ct_vi_tri_uu_tien'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phieunhap_ct',
            name='vi_tri_uu_tien',
        ),
        migrations.CreateModel(
            name='PhieuNhap_CT_Allocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_luong', models.IntegerField(default=0, verbose_name='Số lượng phân bổ')),
                ('phieu_nhap_ct', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='kho.phieunhap_ct')),
                ('vi_tri', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='danh_muc.vitrikho', verbose_name='Vị trí ô kệ')),
            ],
            options={
                'verbose_name': 'Phân bổ vị trí chi tiết',
                'db_table': 'kho_phieunhap_ct_allocation',
            },
        ),
    ]
