# Generated by Django 5.1.6 on 2026-04-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0014_remove_phieunhap_ct_vi_tri_uu_tien_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieunhap_ct_allocation',
            name='ma_vi_tri',
            field=models.CharField(blank=True, max_length=20, verbose_name='Mã vị trí'),
        ),
        migrations.AlterField(
            model_name='phieunhap',
            name='loai_nhap',
            field=models.CharField(choices=[('1', 'Mua nhà cung cấp'), ('2', 'Khách hàng trả hàng'), ('3', 'Nhập chênh lệch kiểm kê')], default='1', max_length=20, verbose_name='Loại nhập'),
        ),
        migrations.AlterField(
            model_name='phieuxuat',
            name='loai_xuat',
            field=models.CharField(choices=[('ban_hang', 'Xuất bán hàng'), ('tra_ncc', 'Trả nhà cung cấp'), ('noi_bo', 'Xuất nội bộ'), ('hu_hong', 'Hư hỏng / Hao hụt'), ('kiem_ke', 'Xuất chênh lệch kiểm kê')], default='ban_hang', max_length=20, verbose_name='Loại xuất'),
        ),
    ]
