# Generated by Django 5.1.6 on 2026-04-26 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0015_phieunhap_ct_allocation_ma_vi_tri_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phieunhap_ct_allocation',
            name='ma_vi_tri',
            field=models.CharField(default='', max_length=50, verbose_name='Mã vị trí'),
        ),
    ]
