# Generated by Django 5.1.6 on 2026-04-28 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kho', '0016_alter_phieunhap_ct_allocation_ma_vi_tri'),
    ]

    operations = [
        migrations.AddField(
            model_name='phieuxuat_ct',
            name='gia_xuat',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Giá xuất'),
        ),
        migrations.AddField(
            model_name='phieuxuat_ct',
            name='tong_tien',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Tổng tiền'),
        ),
    ]
