# Generated by Django 5.1.6 on 2026-05-06 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('danh_muc', '0010_khachhang_la_nhan_vien'),
        ('kho', '0017_phieuxuat_ct_gia_xuat_phieuxuat_ct_tong_tien'),
    ]

    operations = [
        migrations.AddField(
            model_name='kiemke',
            name='hang_hoa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.hanghoa', verbose_name='Hàng hóa kiểm kê'),
        ),
    ]
