# Generated by Django 5.1.6 on 2026-04-10 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('danh_muc', '0010_khachhang_la_nhan_vien'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(max_length=30, unique=True, verbose_name='So chung tu ghi so')),
                ('document_type', models.CharField(choices=[('hoa_don_ban', 'Hoa don ban hang'), ('phieu_thu', 'Phieu thu'), ('phieu_nhap', 'Phieu nhap kho'), ('phieu_xuat', 'Phieu xuat kho'), ('phieu_dieu_chinh_kho', 'Phieu dieu chinh kho'), ('hang_ban_tra_lai', 'Hang ban bi tra lai'), ('dao_but_toan', 'Dao but toan')], max_length=40, verbose_name='Loai chung tu')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID chung tu nguon')),
                ('document_number', models.CharField(blank=True, max_length=50, verbose_name='So chung tu nguon')),
                ('document_date', models.DateField(verbose_name='Ngay chung tu')),
                ('posting_date', models.DateField(verbose_name='Ngay ghi so')),
                ('description', models.TextField(blank=True, verbose_name='Dien giai')),
                ('status', models.CharField(choices=[('posted', 'Da ghi so'), ('reversed', 'Da dao')], default='posted', max_length=20, verbose_name='Trang thai')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.khachhang', verbose_name='Khach hang')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Nguoi ghi so')),
                ('reversed_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverse_of', to='so_cai.journalentry', verbose_name='Chung tu dao')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.nhacungcap', verbose_name='Nha cung cap')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.kho', verbose_name='Kho')),
            ],
            options={
                'verbose_name': 'Chung tu ghi so',
                'verbose_name_plural': 'Chung tu ghi so',
                'db_table': 'so_cai_journal_entry',
                'ordering': ['-posting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='JournalEntryLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(default=1, verbose_name='So dong')),
                ('debit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phat sinh no')),
                ('credit_amount', models.DecimalField(decimal_places=0, default=0, max_digits=18, verbose_name='Phat sinh co')),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='danh_muc.taikhoanketoan', verbose_name='Tai khoan')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.khachhang')),
                ('journal_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='so_cai.journalentry')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.nhacungcap')),
                ('warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='danh_muc.kho')),
            ],
            options={
                'verbose_name': 'Dong but toan',
                'verbose_name_plural': 'Dong but toan',
                'db_table': 'so_cai_journal_entry_line',
                'ordering': ['journal_entry_id', 'line_no', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['document_type', 'document_id'], name='so_cai_jour_documen_c891af_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['posting_date'], name='so_cai_jour_posting_d496e9_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentry',
            index=models.Index(fields=['document_number'], name='so_cai_jour_documen_082099_idx'),
        ),
        migrations.AddConstraint(
            model_name='journalentry',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'posted'), models.Q(('document_type', 'dao_but_toan'), _negated=True)), fields=('document_type', 'document_id'), name='uniq_so_cai_posted_per_document'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['account'], name='so_cai_jour_account_18062c_idx'),
        ),
        migrations.AddIndex(
            model_name='journalentryline',
            index=models.Index(fields=['journal_entry', 'line_no'], name='so_cai_jour_journal_bab701_idx'),
        ),
    ]
