# Generated by Django 5.1.6 on 2026-04-15 02:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('so_cai', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='KyKeToan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nam', models.PositiveIntegerField(verbose_name='Năm tài chính')),
                ('ky_so', models.PositiveSmallIntegerField(verbose_name='Kỳ số')),
                ('ten_ky', models.CharField(max_length=50, verbose_name='Tên kỳ')),
                ('tu_ngay', models.DateField(verbose_name='Từ ngày')),
                ('den_ngay', models.DateField(verbose_name='Đến ngày')),
                ('trang_thai', models.CharField(choices=[('open', 'Đang mở'), ('locked', 'Đã khóa')], default='open', max_length=20, verbose_name='Trạng thái')),
                ('ghi_chu', models.CharField(blank=True, max_length=255, verbose_name='Ghi chú')),
                ('khoa_luc', models.DateTimeField(blank=True, null=True, verbose_name='Khóa lúc')),
                ('ngay_tao', models.DateTimeField(auto_now_add=True)),
                ('ngay_cap_nhat', models.DateTimeField(auto_now=True)),
                ('khoa_boi', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ky_ke_toan_khoa_boi', to=settings.AUTH_USER_MODEL, verbose_name='Khóa bởi')),
                ('nguoi_tao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ky_ke_toan_tao', to=settings.AUTH_USER_MODEL, verbose_name='Người tạo')),
            ],
            options={
                'verbose_name': 'Kỳ kế toán',
                'verbose_name_plural': 'Kỳ kế toán',
                'db_table': 'so_cai_ky_ke_toan',
                'ordering': ['-nam', 'ky_so'],
                'unique_together': {('nam', 'ky_so')},
            },
        ),
    ]
